In [3]:
import numpy as np

a = np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
b = a[::,1]
b

array([ 1,  5,  9, 13])

In [5]:
c = a[2,1:]
c

array([ 9, 10, 11])

In [7]:
d = a[:2,:2]
d

array([[0, 1],
       [4, 5]])

In [8]:
e = a[1:3,1:3]
e

array([[ 5,  6],
       [ 9, 10]])

In [28]:
f1 = a[0,:3]
f2 = a[1,:3]
f = np.append(f1,f2)
f

array([0, 1, 2, 4, 5, 6])

In [29]:
g1 = a[2,:]
g2 = a[3,:]
g = np.append(g1,g2)
g

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
h1 = a[1,1:]
h2 = a[3,1:]
h = np.append(h1,h2)
h

array([ 5,  6,  7, 13, 14, 15])