In [3]:
import numpy as np

a = np.array(np.random.randint(1,100,size=15),dtype=np.int64).reshape(3,5)
a

array([[26, 14,  8, 62,  7],
       [68, 47,  1, 42, 54],
       [97,  4,  3, 96, 44]], dtype=int64)

In [8]:
a.max(axis=0)

array([97, 47,  8, 96, 54], dtype=int64)

In [7]:
a.min(axis=0)

array([26,  4,  1, 42,  7], dtype=int64)

In [9]:
a.mean(axis=0)

array([63.66666667, 21.66666667,  4.        , 66.66666667, 35.        ])

In [10]:
a.max(axis=1)

array([62, 68, 97], dtype=int64)

In [11]:
a.min(axis=1)

array([7, 1, 3], dtype=int64)

In [12]:
a.mean(axis=1)

array([23.4, 42.4, 48.8])