In [17]:
import numpy as np

a = np.arange(0,24).reshape(4,3,2)
print("index","\t\t","element")
for b in np.ndindex(4,3,2) :
    print(b,"\t",a[b])

index 		 element
(0, 0, 0) 	 0
(0, 0, 1) 	 1
(0, 1, 0) 	 2
(0, 1, 1) 	 3
(0, 2, 0) 	 4
(0, 2, 1) 	 5
(1, 0, 0) 	 6
(1, 0, 1) 	 7
(1, 1, 0) 	 8
(1, 1, 1) 	 9
(1, 2, 0) 	 10
(1, 2, 1) 	 11
(2, 0, 0) 	 12
(2, 0, 1) 	 13
(2, 1, 0) 	 14
(2, 1, 1) 	 15
(2, 2, 0) 	 16
(2, 2, 1) 	 17
(3, 0, 0) 	 18
(3, 0, 1) 	 19
(3, 1, 0) 	 20
(3, 1, 1) 	 21
(3, 2, 0) 	 22
(3, 2, 1) 	 23


In [21]:
np.concatenate((a[0,0],a[1,0]),axis=None)

array([0, 1, 6, 7])

In [23]:
np.concatenate((a[0,0],a[2,1]),axis=None)

array([ 0,  1, 14, 15])

In [42]:
np.concatenate((a[0],a[1]),axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [43]:
np.concatenate((a[0],a[1]),axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])