In [11]:
import numpy as np

a = np.array(range(1,11))
b = a[np.array([1,3,5,7])]

In [12]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
b

array([2, 4, 6, 8])

In [33]:
b = a[5:10]
b

array([ 6,  7,  8,  9, 10])

In [34]:
c = a[6:10]
c

array([ 7,  8,  9, 10])

In [21]:
d = a[0:3]
d

array([1, 2, 3])

In [36]:
e = a[::2]
e

array([1, 3, 5, 7, 9])

In [37]:
f = a[::-2]
f

array([10,  8,  6,  4,  2])