In [12]:
import numpy as np
num = range(1,10)
a = np.array([num[0:3],num[3:6],num[6:9]],dtype=np.int64)
print(a)
b = np.array([[2,2,2],[2,2,2],[2,2,2]],dtype=np.int64)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [13]:
a+b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int64)

In [14]:
a-b

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]], dtype=int64)

In [15]:
a*b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]], dtype=int64)

In [25]:
a/b

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [24]:
(a/b).dtype

dtype('float64')

In [17]:
a@b

array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]], dtype=int64)

In [18]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int64)