In [40]:
import numpy as np

a = np.array([23,45,67,7,2,30,34,82],dtype=np.int64)
print("a = ")
a

a = 


array([23, 45, 67,  7,  2, 30, 34, 82], dtype=int64)

In [41]:
print("최댓값")
a.max()

최댓값


82

In [42]:
print("최솟값")
a.min()

최솟값


2

In [43]:
print("평균")
a.mean()

평균


36.25

In [60]:
b= np.array(np.random.randint(0,99,size=10),dtype=np.int64)
b

array([69,  6,  2, 67, 79, 77, 17, 54, 42, 27], dtype=int64)

In [61]:
print("최댓값")
b.max()

최댓값


79

In [64]:
print("최솟값")
b.min()

최솟값


2

In [63]:
print("mean")
b.mean()

mean


44.0

In [66]:
np.append(a,b)

array([23, 45, 67,  7,  2, 30, 34, 82, 69,  6,  2, 67, 79, 77, 17, 54, 42,
       27], dtype=int64)